version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt-get update
      - apt-get install -y nodejs npm
  build:
    commands:
      - echo "Building the application"
      - npm install
      - npm run build
  post_build:
    commands:
      - echo "Build complete"
      - echo "Ready for deployment"
artifacts:
  files:
    - '**/*'
